version: "2"

services:
  app:
    image: 'sukanya88/onlineayurveda.jar:latest'
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - db    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/training
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Sukany@4323
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Sukany@4323
      - POSTGRES_DB=training
     
    expose:
      - "5432:5432" 

      
